### ISSUE TITLE
Showing all of the pulled tweets at once

### ISSUE THREAD

**Issue by toothie96** [AdamMoses-GitHub/MMM-TweetsByTimelineOrList#3]
I've just installed this module, and found that it cycles between two sets of tweets, the first set (of four) appear to be the same tweets every time, and the second set is showing all of the pulled tweets at once, which spans across the entire mirror. I've set the 'show tweets at a time' to 4. Any ideas? Cheers.

**Comment by AdamMoses-GitHub** [comment]
Hmm, not sure about this one. Could you include some screenshots and the config you are using?

My guess is maybe some error with how many tweets are fetched but that's just a guess until I see more.

**Comment by tommielee40** [comment]
I'm having this same issue, attached you will find my config file as well as 3 screenshots. These are the only three things the module will cycle through. I have taken out all modules and only ran the twitter module by itself and still the same issue.

**Comment by tommielee40** [comment]
[Tweet Debug.txt](https://github.com/AdamMoses-GitHub/MMM-TweetsByTimelineOrList/files/3323559/Tweet.Debug.txt)
