### ISSUE TITLE
Umlaute missing

### ISSUE THREAD

**Issue by KaitoCross** [AdamMoses-GitHub/MMM-TweetsByTimelineOrList#4]
Hello everyone :D Using the module in germany, i discovered that it doesn't display any äöü or ß. I can imagine, that other character's variations of several european languages can not be displayed correctly as well :D
Please fix it :)

**Comment by AdamMoses-GitHub** [comment]
Hmm, I'll take a look at this. I'm surprised the correct character set isn't just adopted automatically.

**Comment by AdamMoses-GitHub** [comment]
Please do an update, there is now a config option "allowSpecialCharacters" that can be set to true and should resolve the problem.
