### ISSUE TITLE
Special characters not showing

### ISSUE THREAD

**Issue by Manuel5cc** [AdamMoses-GitHub/MMM-TweetsByTimelineOrList#6]
The module works but when there is a tweet with special characters (like á, é, etc.) those characters are omitted.

**Comment by thiemt** [comment]
I think something like 

```
function HtmlEncode(s) 
{
  var el = document.createElement("div");
  el.innerText = el.textContent = s;
  s = el.innerHTML;
  return s;
} 
```

Would do the job.
But I have no idea where I need to convert the input. Would be great to get support from @AdamMoses-GitHub here.

**Comment by AdamMoses-GitHub** [comment]
Apologies, I've been meaning to clean this up. My code is pretty aggressive about cleaning the string before displaying but I'll check go over that and try and get this working.

**Comment by thiemt** [comment]
I already fixed it by decode/encodeURI. So I decode the input from twitter and encode it before displaying. 
Is doing the Job, but is more a workaround. If u want I can push it, but I am sure that the real fix need to be done somewhere else.

**Comment by joaquinseco** [comment]
Hi thiemt: Could you please paste the code you modified in the Module?. Thank you very much in advanced!! Joaquin

**Comment by AdamMoses-GitHub** [comment]
Please do an update, there is now a config option "allowSpecialCharacters" that can be set to true and should resolve the problem.

**Comment by joaquinseco** [comment]
Thank you very much @AdamMoses-GitHub !!! It´s working now!!
